# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bn2d9tOLeGOStHYFAlUvs3G6YZ45bn8M
"""

# compare ensemble to each baseline classifier
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import StackingClassifier
from matplotlib import pyplot
from google.colab import files
import io
import pandas as pd


 
# get the dataset
def get_dataset():

	''' Colab Version
	uploaded = files.upload()
	train_file = pd.read_csv(io.BytesIO(uploaded['train.csv']))'''

	train_file = pd.read_csv("/Users/miranda/PycharmProjects/pythonProject8/train.csv")
	train_file = train_file[train_file.asker_reputation != 0]
	train_file = train_file[train_file.views !=0]

	train_file["asker_reputation"].fillna(0, inplace = True)
	
	train_file["views"].fillna(0, inplace = True)
 
	train_file["Text-Code Ratio"].fillna(0, inplace = True)
 
	train_file["Text"].fillna(0, inplace = True)
 
	train_file["Code"].fillna(0, inplace = True)

	

	X = train_file.loc[:,["asker_reputation", "views", "Text-Code Ratio", "Text", "Code"]].values

	y = train_file.loc[:,["Y"]].values

	return X, y
 
# get a stacking ensemble of models
def get_stacking():
	# define the base models
	level0 = list()
	level0.append(('lr', LogisticRegression()))
	level0.append(('knn', KNeighborsClassifier()))
	level0.append(('cart', DecisionTreeClassifier()))
	level0.append(('bayes', GaussianNB()))
	level0.append(('svc', SVC()))
	# define meta learner model
	level1 = LogisticRegression()
	# define the stacking ensemble
	model = StackingClassifier(estimators=level0, final_estimator=level1, cv=5)
	return model
 
# get a list of models to evaluate
def get_models():
	models = dict()
	models['lr'] = LogisticRegression()
	models['knn'] = KNeighborsClassifier()
	models['cart'] = DecisionTreeClassifier()
	models['bayes'] = GaussianNB()
	models['svc'] = SVC()
	models['stacking'] = get_stacking()
	return models
 
# evaluate a give model using cross-validation
def evaluate_model(model, X, y):
	cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
	scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
	return scores
 
# define dataset
X, y = get_dataset()
# get the models to evaluate
models = get_models()
# evaluate the models and store results
results, names = list(), list()
for name, model in models.items():
	scores = evaluate_model(model, X, y)
	results.append(scores)
	names.append(name)
	print('>%s %.3f (%.3f)' % (name, mean(scores), std(scores)))
# plot model performance for comparison
pyplot.boxplot(results, labels=names, showmeans=True)
pyplot.show()